export const iranCities = [
  { value: "آذربایجان شرقی", label: "آذربایجان شرقی" },
  { value: "آذربایجان غربی", label: "آذربایجان غربی" },
  { value: "اردبیل", label: "اردبیل" },
  { value: "اصفهان", label: "اصفهان" },
  { value: "البرز", label: "البرز" },
  { value: "ایلام", label: "ایلام" },
  { value: "بوشهر", label: "بوشهر" },
  { value: "تهران", label: "تهران" },
  { value: "چهارمحال و بختیاری", label: "چهارمحال و بختیاری" },
  { value: "خراسان جنوبی", label: "خراسان جنوبی" },
  { value: "خراسان رضوی", label: "خراسان رضوی" },
  { value: "خراسان شمالی", label: "خراسان شمالی" },
  { value: "خوزستان", label: "خوزستان" },
  { value: "زنجان", label: "زنجان" },
  { value: "سمنان", label: "سمنان" },
  { value: "سیستان و بلوچستان", label: "سیستان و بلوچستان" },
  { value: "فارس", label: "فارس" },
  { value: "قزوین", label: "قزوین" },
  { value: "قم", label: "قم" },
  { value: "کردستان", label: "کردستان" },
  { value: "کرمان", label: "کرمان" },
  { value: "کرمانشاه", label: "کرمانشاه" },
  { value: "کهگیلویه و بویراحمد", label: "کهگیلویه و بویراحمد" },
  { value: "گلستان", label: "گلستان" },
  { value: "گیلان", label: "گیلان" },
  { value: "لرستان", label: "لرستان" },
  { value: "مازندران", label: "مازندران" },
  { value: "مرکزی", label: "مرکزی" },
  { value: "هرمزگان", label: "هرمزگان" },
  { value: "همدان", label: "همدان" },
  { value: "یزد", label: "یزد" },
];

export const iransodoor = [
  { value: "آذربایجان شرقی", label: "آذربایجان شرقی" },
  { value: "آذربایجان غربی", label: "آذربایجان غربی" },
  { value: "اردبیل", label: "اردبیل" },
  { value: "اصفهان", label: "اصفهان" },
  { value: "البرز", label: "البرز" },
  { value: "ایلام", label: "ایلام" },
  { value: "بوشهر", label: "بوشهر" },
  { value: "تهران", label: "تهران" },
  { value: "چهارمحال و بختیاری", label: "چهارمحال و بختیاری" },
  { value: "خراسان جنوبی", label: "خراسان جنوبی" },
  { value: "خراسان رضوی", label: "خراسان رضوی" },
  { value: "خراسان شمالی", label: "خراسان شمالی" },
  { value: "خوزستان", label: "خوزستان" },
  { value: "زنجان", label: "زنجان" },
  { value: "سمنان", label: "سمنان" },
  { value: "سیستان و بلوچستان", label: "سیستان و بلوچستان" },
  { value: "فارس", label: "فارس" },
  { value: "قزوین", label: "قزوین" },
  { value: "قم", label: "قم" },
  { value: "کردستان", label: "کردستان" },
  { value: "کرمان", label: "کرمان" },
  { value: "کرمانشاه", label: "کرمانشاه" },
  { value: "کهگیلویه و بویراحمد", label: "کهگیلویه و بویراحمد" },
  { value: "گلستان", label: "گلستان" },
  { value: "گیلان", label: "گیلان" },
  { value: "لرستان", label: "لرستان" },
  { value: "مازندران", label: "مازندران" },
  { value: "مرکزی", label: "مرکزی" },
  { value: "هرمزگان", label: "هرمزگان" },
  { value: "همدان", label: "همدان" },
  { value: "یزد", label: "یزد" },
];

// constants.js
export const grades = [
  { label: "انتخاب پایه", value: "" }, // این خط مهم است!
  { label: "دهم", value: "10" },
  { label: "یازدهم", value: "11" },
  { label: "دوازدهم", value: "12" },
];

export const majors = [
  { value: "ریاضی", label: "ریاضی" },
  { value: "تجربی", label: "تجربی" },
  { value: "انسانی", label: "انسانی" },
  { value: "معارف", label: "معارف" },
];

export const alefOptions = [
  { value: "ا", label: "ا" },
  { value: "ب", label: "ب" },
  { value: "پ", label: "پ" },
  { value: "ت", label: "ت" },
  { value: "ث", label: "ث" },
  { value: "ج", label: "ج" },
  { value: "چ", label: "چ" },
  { value: "ح", label: "ح" },
  { value: "خ", label: "خ" },
  { value: "د", label: "د" },
  { value: "ذ", label: "ذ" },
  { value: "ر", label: "ر" },
  { value: "ز", label: "ز" },
  { value: "ژ", label: "ژ" },
  { value: "س", label: "س" },
  { value: "ش", label: "ش" },
  { value: "ص", label: "ص" },
  { value: "ض", label: "ض" },
  { value: "ط", label: "ط" },
  { value: "ظ", label: "ظ" },
  { value: "ع", label: "ع" },
  { value: "غ", label: "غ" },
  { value: "ف", label: "ف" },
  { value: "ق", label: "ق" },
  { value: "ک", label: "ک" },
  { value: "گ", label: "گ" },
  { value: "ل", label: "ل" },
  { value: "م", label: "م" },
  { value: "ن", label: "ن" },
  { value: "و", label: "و" },
  { value: "ه", label: "ه" },
  { value: "ی", label: "ی" },
];
